name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl